---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.8
  - name: centos-7
  - name: windows2012r2

suites:
- name: client
  run_list: ["recipe[opsview_client_test::test]"]
  attributes: { 'opsview' : { 'server_url' : 'uat.opsview.com' } }
