driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["winrm_port"] %>
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2

verifier:
  name: inspec

- name: win_client
  run_list:
    - recipe[opsview_client_test]
  includes:
    - windows2012r2
